mutation addTransaction(
  $amount: money = ""
  $ticket_id: uuid = ""
  $user: uuid = ""
) {
  insert_transaction_one(
    object: {
      amount: $amount
      ticket_id: $ticket_id
      user: $user
      status: "OPEN"
    }
  ) {
    id
    status
    amount
  }
}
